[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "test_issue"
dynamic = ["version"]

[tool.setuptools_scm]
# version_scheme= "post-release"
# local_scheme = "no-local-version"
